
version: '3.9'
services:
  dagsterdev:
    build:
      context: ..
      dockerfile: dagster/docker/Dockerfile
      target: dev
    image: taxi_trips
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      AWS_PROFILE: ${AWS_PROFILE}
    volumes:
      - ./:/usr/src/app
      - ~/.aws:/root/.aws