name: "Mesh experience plane release"

on:
  push:
    tags:
      - v*

jobs:
  terraform-modules-oci-release:
    uses: ./.github/workflows/terraform-modules-oci-release.yml
    with:
        organization_layer_name: platform
        team_name: mesh-experience-plane
        products_path: "products"